#!/bin/sh
#
# do history filtering on ldmx-sw
# assumes git-filter-repo is installed

set -o nounset
set -o errexit

git clone --mirror git@github.com:LDMX-Software/G4DarkBreM.git
git clone git@github.com:LDMX-Software/ldmx-sw.git

git -C G4DarkBreM.git remote set-url origin git@github.com:tomeichlersmith/G4DarkBreM.git
git -C G4DarkBreM.git push --mirror
git -C G4DarkBreM.git remote set-url origin git@github.com:LDMX-Software/G4DarkBreM.git

git -C ldmx-sw remote set-url origin git@github.com:tomeichlersmith/ldmx-sw.git
git -C ldmx-sw push --mirror
git -C ldmx-sw remote set-url origin git@github.com:LDMX-Software/G4DarkBreM.git
