#!/bin/sh
#
# mirror repos locally and into private GitHub for insurance

set -o nounset
set -o errexit

git clone --mirror git@github.com:LDMX-Software/G4DarkBreM.git
git clone --mirror git@github.com:LDMX-Software/ldmx-sw.git

git -C G4DarkBreM.git remote set-url origin git@github.com:tomeichlersmith/G4DarkBreM.git
# allow push to fail, expect user to double check mirror
git -C G4DarkBreM.git push --mirror || true
git -C G4DarkBreM.git remote set-url origin git@github.com:LDMX-Software/G4DarkBreM.git

git -C ldmx-sw.git remote set-url origin git@github.com:tomeichlersmith/ldmx-sw.git
# allow push to fail, expect user to double check mirror
git -C ldmx-sw.git push --mirror || true
git -C ldmx-sw.git remote set-url origin git@github.com:LDMX-Software/ldmx-sw.git
